# Generated by Django 2.2.2 on 2019-06-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='stauts',
            new_name='status',
        ),
    ]
