# Generated by Django 2.2.2 on 2019-07-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190710_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(max_length=100, verbose_name='网站'),
        ),
    ]
